AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Environment:
      Type: String
      Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  LambdaVersion:
      Type: "AWS::Lambda::Version"
      Properties:
        FunctionName : arn:aws:lambda:us-east-1:954459734159:function:awscodestar-binance-bot-lambda-HelloWorld-16Q9TC43G164R
  BinanceBot:
    Type: AWS::Serverless::Function
    Description: 'a funky func'
    Properties:
      AutoPublishAlias: devers
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          NODE_ENV: !Ref 'Environment'
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post